-- MySQL Script generated by MySQL Workbench
-- Sun Oct 30 18:30:46 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Surveydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Surveydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Surveydb` DEFAULT CHARACTER SET utf8 ;
USE `Surveydb` ;

-- -----------------------------------------------------
-- Table `Surveydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Surveydb`.`User` (
  `Name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  `user_id_encrypted` INT NOT NULL,
  `user_type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC) VISIBLE,
  UNIQUE INDEX `user_id_encrypted_UNIQUE` (`user_id_encrypted` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Surveydb`.`Survey`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Surveydb`.`Survey` (
  `idSurvey` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(300) NULL,
  `num_of_questions` INT NOT NULL,
  `owner_id` INT NOT NULL,
  PRIMARY KEY (`idSurvey`),
  UNIQUE INDEX `idSurvey_UNIQUE` (`idSurvey` ASC) VISIBLE,
  INDEX `fk_Survey_User_idx` (`owner_id` ASC) VISIBLE,
  CONSTRAINT `fk_Survey_User`
    FOREIGN KEY (`owner_id`)
    REFERENCES `Surveydb`.`User` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Surveydb`.`Question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Surveydb`.`Question` (
  `ID` INT NOT NULL,
  `Question_Title` VARCHAR(45) NOT NULL,
  `Question_Text` VARCHAR(1000) NOT NULL,
  `Amount_of_options` INT NOT NULL,
  `Number_of_question` INT NOT NULL,
  `Survey_idSurvey` INT NOT NULL,
  `Amount_Answered` INT NULL,
  PRIMARY KEY (`ID`, `Survey_idSurvey`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Question_Survey1_idx` (`Survey_idSurvey` ASC) VISIBLE,
  CONSTRAINT `fk_Question_Survey1`
    FOREIGN KEY (`Survey_idSurvey`)
    REFERENCES `Surveydb`.`Survey` (`idSurvey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Surveydb`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Surveydb`.`Answer` (
  `ID` INT NOT NULL,
  `Amount_Chosen` INT NULL,
  `Percent_Chosen` DECIMAL NULL,
  `additional_info` VARCHAR(100) NULL,
  `Answer_text` VARCHAR(300) NOT NULL,
  `Question_ID` INT NOT NULL,
  `Question_Survey_idSurvey` INT NOT NULL,
  PRIMARY KEY (`ID`, `Question_ID`, `Question_Survey_idSurvey`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  INDEX `fk_Answer_Question1_idx` (`Question_ID` ASC, `Question_Survey_idSurvey` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_Question1`
    FOREIGN KEY (`Question_ID` , `Question_Survey_idSurvey`)
    REFERENCES `Surveydb`.`Question` (`ID` , `Survey_idSurvey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
